In [1]:
# Importing essential libraries
import pandas as pd  # For handling and manipulating structured data (dataframes)
import matplotlib.pyplot as plt  # For data visualization (graphs and plots)
import numpy as np  # For numerical computations (arrays, mathematical operations)
import seaborn as sns  # For advanced data visualization (heatmaps, pair plots, etc.)
import string  # For handling string operations (e.g., punctuation removal)
import re  # For working with regular expressions (text pattern matching)

# Importing machine learning utilities from scikit-learn
from sklearn.model_selection import train_test_split  # For splitting data into training and testing sets
from sklearn.metrics import accuracy_score  # For calculating model accuracy
from sklearn.metrics import classification_report  # For generating a detailed classification performance report

In [2]:
# Loading the datasets from the specified file paths

# Reading the "Fake.csv" file into a pandas DataFrame
fake = pd.read_csv(r"C:\Users\91969\OneDrive\Documents\Fake Newz Det/Fake.csv")

# Reading the "True.csv" file into a pandas DataFrame
true = pd.read_csv(r"C:\Users\91969\OneDrive\Documents\Fake Newz Det/True.csv")

In [3]:
fake.shape

(23481, 4)

In [4]:
true.shape

(21417, 4)

In [5]:
fake.head(10)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017"
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017"
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017"
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017"
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017"

In [6]:
true.head(10)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017"
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017"
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017"

In [7]:
fake.tail(10)

,title,text,subject,date
23471,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016"
23472,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016"
23473,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016"
23474,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016"
23475,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016"
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [8]:
true.tail()

,title,text,subject,date
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [9]:
# Adding a new column 'class' to label the data

# Assigning the label 0 to all rows in the "fake" DataFrame (indicating fake news)
fake["class"] = 0  

# Assigning the label 1 to all rows in the "true" DataFrame (indicating true news)
true["class"] = 1

In [10]:
# Selecting the last 10 rows from the "fake" DataFrame for manual testing
fake_manual_testing = fake.tail(10)

# Removing the last 10 rows from the "fake" DataFrame to prevent data leakage
for i in range(23480, 23470, -1):  # Looping backwards from index 23480 to 23471
    fake.drop([i], axis=0, inplace=True)  # Dropping the specified rows

# Selecting the last 10 rows from the "true" DataFrame for manual testing
true_manual_testing = true.tail(10)

# Removing the last 10 rows from the "true" DataFrame to prevent data leakage
for i in range(21416, 21406, -1):  # Looping backwards from index 21416 to 21407
    true.drop([i], axis=0, inplace=True)  # Dropping the specified rows

In [11]:
fake.head()

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [12]:
fake.shape, true.shape

((23471, 5), (21407, 5))

In [13]:
fake_manual_testing['class']=0
true_manual_testing['class']=1

C:\Users\91969\AppData\Local\Temp\ipykernel_1172\1287159230.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fake_manual_testing['class']=0
C:\Users\91969\AppData\Local\Temp\ipykernel_1172\1287159230.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  true_manual_testing['class']=1

In [14]:
fake_manual_testing.head(10)

,title,text,subject,date,class
23471,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016",0
23472,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016",0
23473,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016",0
23474,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016",0
23475,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016",0
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [15]:
true_manual_testing.head(10)

,title,text,subject,date,class
21407,"Mata Pires, owner of embattled Brazil builder ...","SAO PAULO (Reuters) - Cesar Mata Pires, the ow...",worldnews,"August 22, 2017",1
21408,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21409,"U.S., North Korea clash at U.N. arms forum on ...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21410,Headless torso could belong to submarine journ...,COPENHAGEN (Reuters) - Danish police said on T...,worldnews,"August 22, 2017",1
21411,North Korea shipments to Syria chemical arms a...,UNITED NATIONS (Reuters) - Two North Korean sh...,worldnews,"August 21, 2017",1
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [16]:
# Merging the "fake" and "true" datasets into a single DataFrame

merge = pd.concat([fake, true], axis=0)  # Concatenating along rows (axis=0)

# Displaying the first 10 rows of the merged dataset
merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [17]:
# Displaying the column names of the merged DataFrame
merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [18]:
# Dropping unnecessary columns from the merged dataset

data = merge.drop(['title', 'subject', 'date'], axis=1)

In [19]:
# Checking for missing (null) values in the dataset
data.isnull().sum()

text     0
class    0
dtype: int64

In [20]:
# Shuffling the dataset randomly
data = data.sample(frac=1)

In [21]:
data.head()

                                                    text  class
6447   North Carolina Republicans should have listene...      0
10868  Just two months shy of the one-year anniversar...      0
4624   WASHINGTON (Reuters) - President Donald Trump ...      1
23298   Press Association The GuardianFilm director O...      0
13863  We ve heard from this local anchor before. He ...      0

In [22]:
# Resetting the index after shuffling
data.reset_index(inplace=True)

# Dropping the old index column that was created during the reset
data.drop(['index'], axis=1, inplace=True)

In [23]:
# Displaying the column names of the DataFrame
data.columns

Index(['text', 'class'], dtype='object')

In [24]:
data.head()

                                                text  class
0  North Carolina Republicans should have listene...      0
1  Just two months shy of the one-year anniversar...      0
2  WASHINGTON (Reuters) - President Donald Trump ...      1
3   Press Association The GuardianFilm director O...      0
4  We ve heard from this local anchor before. He ...      0

In [25]:
import re
import string

def wordopt(text):
    """
    Preprocesses a given text by removing unnecessary elements such as 
    punctuation, URLs, numbers, and special characters.
    Args:
    text (str): The input text string to be cleaned.
    Returns:
    str: The cleaned and processed text.
    """
    # Convert text to lowercase to ensure uniformity
    text = text.lower()
    # Remove text within square brackets (e.g., citations like [1], [example])
    text = re.sub(r'\[.*?\]', '', text)  
    # Remove non-word characters (anything that is not a letter or number)
    text = re.sub(r"\W", " ", text)    
    # Remove URLs (http, https, or www)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)  
    # Remove HTML tags (e.g., <p>, <br>)
    text = re.sub(r'<.*?>+', '', text)  # (b'' is incorrect, removed that)
    # Remove punctuation marks
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    # Remove words containing numbers (e.g., "word123" or "123word456")
    text = re.sub(r'\w*\d\w*', '', text)
    
    return text

In [26]:
import re
import string

def wordopt(text):
    """
    Preprocesses a given text by removing unnecessary elements such as 
    punctuation, URLs, numbers, and special characters.
    Args:
    text (str): The input text string to be cleaned
    Returns:
    str: The cleaned and processed text.
    """
    # Convert text to lowercase to ensure uniformity
    text = text.lower()
    # Remove text within square brackets (e.g., citations like [1], [example])
    text = re.sub(r'\[.*?\]', '', text)
    # Remove non-word characters (anything that is not a letter or number)
    text = re.sub(r"\W", " ", text) 
    # Remove URLs (http, https, or www)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    # Remove HTML tags (e.g., <p>, <br>)
    text = re.sub(r'<.*?>+', '', text)  # (b'' is incorrect, removed that)
    # Remove punctuation marks
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    # Remove words containing numbers (e.g., "word123" or "123word456")
    text = re.sub(r'\w*\d\w*', '', text)
    return text

In [27]:
# Separating features (text) and target labels (class)
x = data['text']  # Independent variable (news content)
y = data['class']  # Dependent variable (0 = Fake news, 1 = True news)

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Initializing the TF-IDF Vectorizer
vectorization = TfidfVectorizer()
# Fitting the vectorizer to the training data and transforming it into numerical format
xv_train = vectorization.fit_transform(x_train)
# Transforming the test data using the same fitted vectorizer
xv_test = vectorization.transform(x_test)

In [30]:
from sklearn.linear_model import LogisticRegression# Initializing the Logistic Regression model
LR = LogisticRegression()

# Training the model using the TF-IDF transformed training data
LR.fit(xv_train, y_train)

LogisticRegression()

In [31]:
# Initializing the Logistic Regression model
LR = LogisticRegression()

# Training the model using the TF-IDF transformed training data
LR.fit(xv_train, y_train)# Making predictions on the test dataset using the trained Logistic Regression model
pred_lr = LR.predict(xv_test)

In [32]:
# Making predictions on the test dataset using the trained Logistic Regression model
pred_lr = LR.predict(xv_test)

In [33]:
# Evaluating the model's accuracy on the test dataset
LR.score(xv_test, y_test)

0.9854723707664884

In [34]:
# Generating a detailed classification report for model evaluation
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5838
           1       0.98      0.99      0.98      5382

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [35]:
#DECSISON TREE
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [36]:
pred_dt = DT.predict(xv_test)

In [37]:
DT.score(xv_test, y_test)

0.9963458110516934

In [ ]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5838
           1       0.98      0.99      0.98      5382

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [39]:
# Function to return the label based on prediction output
def output_label(n): 
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"
    
# Function for manual testing of a given news article
def manual_testing(news):
    # Create a DataFrame for the input news article
    testing_news = {"text": [news]}
    new_def_test = pd.DataFrame(testing_news)
    
    # Apply text preprocessing (wordopt function should be defined)
    new_def_test['text'] = new_def_test["text"].apply(wordopt)
    
    # Transform the text using the pre-trained vectorizer
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)
    
    # Make predictions using Logistic Regression and Decision Tree models
    pred_LR = LR.predict(new_xv_test)  # Logistic Regression Prediction
    pred_DT = DT.predict(new_xv_test)  # Decision Tree Prediction
    
    # Print predictions from both models
    return print("\n\nLR Prediction: {} \nDT Prediction: {}".format(
        output_label(pred_LR[0]),  # Convert prediction output to label
        output_label(pred_DT[0])   # Convert prediction output to label
    ))

In [40]:
# Taking user input for manual testing
news = str(input("Enter the news article text: "))

# Running the manual testing function on the provided input
manual_testing(news)

Enter the news article text:  India's Manushi Chhillar has won the Miss World beauty pageant for the year 2017. The win comes 17 years after Priyanka Chopra brought home the coveted title in the year 2000. Andrea Meza, who is Miss Mexico was the first runner up and Stephanie Hill from England was second runner up. Around 108 women from across the world participated in the beauty pageant.  Ms Chhillar, a 20-year-old from Haryana, studied in St. Thomas School in New Delhi and Bhagat Phool Singh Government Medical College for Women in Sonepat.  According to Ms Chhillar's profile on the Miss World website, Ms Chhillar aims to be a cardiac surgeon and has plans of opening non-profit hospitals in rural areas.  Ms Chhillar's profile also says she is a trained classical dancer and has a passion for outdoor sports like scuba diving, snorkelling and bungee jumping.

LR Prediction: Fake News
DT Prediction: Fake News